CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname TEXT NULL,
  lastname TEXT NULL,
  email TEXT NULL
);

CREATE TABLE appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  startdate timestamp NULL,
  starttime TEXT NULL,
  enddate timestamp NULL,
  endtime TEXT NULL,
  userid bigint REFERENCES users (id)
);

-- 1st edit
ALTER TABLE users ADD CONSTRAINT constraint_name UNIQUE (email);